BASE_URL = 'https://sede.administracionespublicas.gob.es/icpplus/index.html'
CITIES = {
    "/icpplus/citar?p=15&amp;locale=es": "A Coruña",
    "/icpplus/citar?p=2&amp;locale=es": "Albacete",
    "/icpco/citar?p=3&amp;locale=es": "Alicante",
    "/icpplus/citar?p=4&amp;locale=es": "Almería",
    "/icpplus/citar?p=1&amp;locale=es": "Araba",
    "/icpplus/citar?p=33&amp;locale=es": "Asturias",
    "/icpplus/citar?p=5&amp;locale=es": "Ávila",
    "/icpplus/citar?p=6&amp;locale=es": "Badajoz",
    "/icpplustieb/citar?p=8&amp;locale=es": "Barcelona",
    "/icpplus/citar?p=48&amp;locale=es": "Bizkaia",
    "/icpplus/citar?p=9&amp;locale=es": "Burgos",
    "/icpplus/citar?p=10&amp;locale=es": "Cáceres",
    "/icpplus/citar?p=11&amp;locale=es": "Cádiz",
    "/icpplus/citar?p=39&amp;locale=es": "Cantabria",
    "/icpplus/citar?p=12&amp;locale=es": "Castellón",
    "/icpplus/citar?p=51&amp;locale=es": "Ceuta",
    "/icpplus/citar?p=13&amp;locale=es": "Ciudad Real",
    "/icpplus/citar?p=14&amp;locale=es": "Córdoba",
    "/icpplus/citar?p=16&amp;locale=es": "Cuenca",
    "/icpplus/citar?p=20&amp;locale=es": "Gipuzkoa",
    "/icpplus/citar?p=17&amp;locale=es": "Girona",
    "/icpplus/citar?p=18&amp;locale=es": "Granada",
    "/icpplus/citar?p=19&amp;locale=es": "Guadalajara",
    "/icpplus/citar?p=21&amp;locale=es": "Huelva",
    "/icpplus/citar?p=22&amp;locale=es": "Huesca",
    "/icpco/citar?p=7&amp;locale=es": "Illes Balears",
    "/icpplus/citar?p=23&amp;locale=es": "Jaén",
    "/icpplus/citar?p=26&amp;locale=es": "La Rioja",
    "/icpco/citar?p=35&amp;locale=es": "Las Palmas",
    "/icpplus/citar?p=24&amp;locale=es": "León",
    "/icpplus/citar?p=25&amp;locale=es": "Lleida",
    "/icpplus/citar?p=27&amp;locale=es": "Lugo",
    "/icpplustiem/citar?p=28&amp;locale=es": "Madrid",
    "/icpco/citar?p=29&amp;locale=es": "Málaga",
    "/icpplus/citar?p=52&amp;locale=es": "Melilla",
    "/icpplus/citar?p=30&amp;locale=es": "Murcia",
    "/icpplus/citar?p=31&amp;locale=es": "Navarra",
    "/icpplus/citar?p=32&amp;locale=es": "Orense",
    "/icpplus/citar?p=34&amp;locale=es": "Palencia",
    "/icpplus/citar?p=36&amp;locale=es": "Pontevedra",
    "/icpplus/citar?p=37&amp;locale=es": "Salamanca",
    "/icpco/citar?p=38&amp;locale=es": "S.Cruz Tenerife",
    "/icpplus/citar?p=40&amp;locale=es": "Segovia",
    "/icpplus/citar?p=41&amp;locale=es": "Sevilla",
    "/icpplus/citar?p=42&amp;locale=es": "Soria",
    "/icpplus/citar?p=43&amp;locale=es": "Tarragona",
    "/icpplus/citar?p=44&amp;locale=es": "Teruel",
    "/icpplus/citar?p=45&amp;locale=es": "Toledo",
    "/icpplus/citar?p=46&amp;locale=es": "Valencia",
    "/icpplus/citar?p=47&amp;locale=es": "Valladolid",
    "/icpplus/citar?p=49&amp;locale=es": "Zamora",
    "/icpplus/citar?p=50&amp;locale=es": "Zaragoza"
}